"Abtastung
"Aktuelle
"Alarmzustände
"Bearbeiten"
"Bedienung"
"Beenden"
"Benutzer"
"Betriebsart"
"CC8-Verbindungen"
"Datei"
"Dateiname"
"Debugging
"Default"
"Drucken
"Ebene
"Eingabe"
"Einmess
"FW-ID
"Festlegung
"Firmware
"Frequenz"
"GWF
"Geräte
"Hilfe"
"Kanal
"Knoten"
"Kommunikation
"Konfiguration
"Laden"
"Meldung
"Minimal"
"Neu..."
"Normal"
"Online
"Passwort
"Pegel
"Pfeiltasten"
"Port"
"Prüfschleife
"SISA
"Schnittst
"Sichern
"Speicher
"Standard"
"Startbit"
"Steckplatz"
"Taktprioritäten"
"Test
"Text
"Transparent"
"Umsetze
"Warten
"XMP1
"Zeigen/Drucken"
"synchron
#>enable
(16)
(2)
(4)
(8)
(Add/Drop
(Anzeige
(Buchse)
(Knoten
(Kopierfunktion).
(Persistance
(S-Pl)
(Vor
) angezeigt.
+7 V
- Abtastung
- Auswählen des Umsetzers für den Sie die Einstellungen vornehmen wollen
- Beschalten des Umsetzers
- DSK
- Def
- M
- Zentrale- und dezentrale Steckplatzinformation einstellen
- d
- das
- konfigurieren der
- synchron
- zentrale und dezentrale Steckplatzinformation
-8 V
-UB
.65534)
0,05
0,1
0,15
0,2
0,25
0,3
0,35
0,4
0,5
0,6
0,6; 1,2; 2,4; 4,8; 9,6; 19,2; 48 und 56
0,7
1,0
1,1
10)
12/1/12
12/4/14
16-kbit/s-Kanäle
19,2
192
2,5
2-Mbit/s
2-Mbit/s-Verbindungen
3,0
3.11
3.6
32-kbit/s-Kanäle
4,0
4,8
5,0
5,5
62.
64"
64-kbit-Kanal
64-kbit/s-Kanal
64-kbit/s-Kanäle
64kBit
64kb
8-Bit
8-kbit/s
8-kbit/s-Kanäle
9,6
<0...254>
<Abbrechen>
<Aus
<Ausführen>.
<Beenden>
<CC8
<Ebene>
<Eintrag
<Enter>.
<Lastwert
<Name
<OK>.
<Ok>.
<Schleife
<Senden>.
<Start
<Steckplatz>
<Subadresse>
<Weiter>
<ebene
<platz
<platz>
<sub>
<subadresse>
<Ändern>
<Übernehmen>
ABM
ABM-Funktionen von der Ferne durchführen
Abbrechen
Abfrage
Abfragen der aktuellen Knoteninformation
Abhilfe :
Abschluß
Abtastrate
Abtastung
Abtastung ohne V.110 Rahmen
Achtung
Adapter
Aktive Ebene:
Aktivieren
Aktivierung
Aktuelle Knoteninformation
Aktuellen Alarmzustand abfragen
Alarme
Alarmierung
Alarmzustand
Alle
Als
Anfangs-
Angabe
Angaben
Anklicken
Anschließen des MSP an den XMP1
Anschließend
Anschluß
Antwort
Anzahl
Anzeige
Anzeige GBÜ Daten
Anzeige der
Applikation
Arbeit
Auf
Aufrufen
Ausdruck
Ausführen".
Ausga
Ausschalten einer Prüfschleife
Auswahl
Auswahl der
Auswählen
Bank
Baugruppe
Baugruppen
Baugruppenkonfiguration
Beachten
Beachten Sie die für die Bitrate benötigte Anzahl von Bits im 64-kbit-Kanal bei der Vergabe der Startbits.
Bedarf
Bediener
Bedienung
Beende Refresh-Timer
Beenden
Beendigung
Befehl
Befehle
Bei
Bei der
Bei eine
Beispiel
Bereich
Beschalte
Beschaltung
Beschaltung der Umsetzer
Beschreibung
Besonderheit
Besonderheiten bei der Konfiguration von CC8-Verbindungen, Schnittstelleninformation
Besonderheiten der Kanalbeziehungen
Bestätigung
Bestücken eines neuen Knotens
Bestücken von Baugruppen
Bestückung
Betrieb
Betriebs
Betriebsart
Betriebsart "
Betriebsart "Abtastung
Betriebsart "Default"
Betriebsart "synchron
Betätigen
Betätigen Sie die Schaltfläche <Senden>.
Beziehung
Bild
Bilden
Bit
Bitposition
Bitpositionen
Bitrate
Bitraten
Brechen Sie den Ladevorgang
Button
Bündel prüfen
Bündelnummer
CC8
CC8-Datenmultiplexer
CC8-Grundlagen
CC8-Kanal
CC8-Kanäle
CC8-Konfiguration
CC8-Umsetzern
CC8-Verbindung
CC8-fähigen
CD-Laufwerk
COM-Schnittstelle
CRC4-Verfahren
Check
D-Kanal
D-Kanäle
D-Umsetzer
DSK
DSK-Baugruppe
Dadurch
Damit
Danach
Das
Das Listfeld wird geschlossen und die gewählte Baugruppe wird auf dem Steckplatz eingetragen.
Das Meldefenster
Datei
Dateien
Dateiname
Daten
Datenendgerät
Datensignale
Datenübertragung
Debug-Befehl
Debug-Funktion
Debug-Funktionen für phasenstarre Übertragung
Debugging
Debugging und Soft-ABM
Debugging-/Soft-ABM-Befehl
Debugging-Befehle
Debugging-Funktion
Debugging-Kommandostruktur
Debuggingbefehl
Debuggingfunktionen für allgemeine Einstellungen
Default
Definition
Definition der Betriebsarten
Der
Der Debuggingbefehl wird nun an den Knoten ausgesendet.
Dez. Steckplatzinfo für
Dezentrale Steckplatzinformation
Dialog
Dialog-Beschreibung
Dialogfeld
Dialogfelder Baugruppe
Dialogfelder CC8-Konfiguration
Dialogfelder DSK Baugruppe
Dialogfelder KZU Baugruppe
Dialogfelder Kanalbeziehungen
Dialogfelder Port Baugruppe
Dialogfelder Taktprioritäten
Dialogfelder Zentralteil
Die
Die Bündelnummer kennzeichnet die 2-Mbit/s-Verbindungen zwischen denen Ersatzschaltungen durchgeführt werden können. Ersatzschaltungen können nur bei 2-Mbit/s-Verbindungen mit gleicher Bündelnummer geschaltet werden.
Die CC8-Konfiguration
Die Maske "CC8-Verbindungen" erscheint.
Die Maske "Prüfschleife" erscheint.
Die Maske wird
Die gewählte Taktquelle wird im Eingabefeld aufgelistet.
Dies
Diese
Diese Maske stellt je nach ausgewählter Baugruppe unterschiedliche Einstellungen bereit.
Diese Schaltfläche
Dieser
Dieses
Dieses Passwort darf aus maximal 10 Ziffern bestehen.
Diskette
Doppelklick
Dreieck
Drucke
Drücken
Drücken Sie die Schaltfläche <
Drücken Sie die Schaltfläche <Start Prüfschleife>.
Drücken Sie die Taste <Enter>.
Durch
E&M
Ebene
Ebene schalten
Ebenennummer
Ein
Eingabe
Eingabefeld
Eingabefenster
Eingaben
Eingeben einer neuen Kanalbeziehung
Einleitung
Einmessen
Einmessung
Einsatz
Einschalten einer Prüfschleife
Einschub
Einschubes
Einschubtyp
Einschübe
Einstellen
Einstellen der dezentralen Steckplatzinformation
Einstellen der zentralen Steckplatzinformation
Einstellung
Einstellungen
Einsätze
Eintrag
Eintrag ok
Einzelbit
Einzelkanal-Ersatzschaltung
Empfang
Empfangspegel
Empfangsrichtung
Endknoten
Entfernen einer bestückten Baugruppe
Ergebnis
Ergänzen einer bestehenden Bestückung
Ersatz
Ersatzlage
Ersatzschaltung
Ersatzweg
Erweiterte Konfiguration
Erweiterung der Bedienung
Erweiterungen
Erzeug
Erzeugung der Installationsdisketten
Es 
Es erscheint
Es erscheint d
Es erscheint die Hauptmaske "XMP1".
Es erscheint die Maske "
Es erscheint die Maske "Konfiguration
Es erscheint die Maske "SISA Netzmanager Offline
Es erscheint die Maske "Taktprioritäten". Im Listfeld der beschalteten Ports werden alle im Knoten verfügbaren Taktquellen mit ihren Taktprioritäten aufgelistet. Bei den Taktquellen "Port" werden nur die Ports aufgeführt, die bei der Konfiguration mit "b
Es öffnet sich das Listfeld, in dem alle für die Bestückung des Knotens verfügbaren Baugruppen aufgelistet sind.
Es öffnet sich die
Es öffnet sich ein
F1ab
F1an
FEK
FSP
FW-ID aktiv:
FW-ID der
FW-ID passiv:
Fall
Fehler
Fehlerfall
Fehlermeldung
Feld
Fenster
Ferne
Festlegen
Festlegung
Festplatte
Firmware
Firmware aktivieren
Firmware-ID
Flash-Bank
Flexibler
Folgende
Fremdknoten
Fremdsystem
Frequenz
Funktion
Funktion Debugging / Soft-ABM
Funktion Text mit / ohne Quittung
Funktionen
Funktionen der Lastabwehr
Funktionen,
Funktionsfeld
Funktionstaste
Führen Sie
Für
Für d
Für diese Portschnittstelle ist keine Ersatzschaltung definiert.
G703
GBÜ
GBÜ-Daten
GWF
GWF Ergebnisse abfragen
GWF einmessen
GWF-
Geben
Geben Sie im Feld "Eingabe" den zu versendenden Text ein. Dieser Text darf maximal 70 Zeichen lang sein. Werden mehr als 70 Zeichen eingegeben, dann werden diese am ABM nicht angezeigt.
Geben Sie im Feld "Passwort Eingabe" das neue Passwort ein.
Geben Sie im Listfeld "
Geben Sie im Listfeld "Schnittstelle" die Schnittstelle an, an
Geben Sie nun im Feld "Passwort Verifikation" zur Bestätigung noch einmal das gleiche Passwort ein.
Gegenport
Gegens
Gerät
Gesamtanzahl
Gesamtkonfiguration
Gesamtsystem
Gleichwellenfunk
Grund
Grundausstattung
Gruppenzuordnung
HINWEIS
Handbuch
Hardware
Hardwarevoraussetzungen
Hauptmaske
Hauptmenü
Hauptmenü "Bedienung"
Hauptmenüpunkt
Hauptmenüpunkt "Konfiguration"
Hauptstation
Hersteller
Hier
Hier geben Sie d
Hier geben Sie das Startbit an, ab dem der zu konfigurierende CC8-Kanal im
Hierbei
Hilfe
Hintergrundfarbe
Hinweis
Hole Knotennr. vom angeschl. Knoten
Holen
Häkchen
ISDN
ISDN-Baugruppe
Ihre
Im 
Im Beispiel das Bit
Im Beispiel der Umsetzer
Im Beispiel ist dies d
Im Beispiel sind dies 19
Im Dialogfeld "
Im Feld
Im Feld "Meldung von XMP1" wird die Antwort des Knotens angezeigt.
Im letzten Umsetzer der Pollingstrecke muß in der dezentralen Steckplatzinfo des Umsetzers die Info-Nr. 10 "NF sperren bei ankommendem Bit b" gesetzt werden.
In 
Info-Nr.
Information
Inhalt
Install
Installation
Installation auf Festplatte
Installationsdisketten
Ist
Istzustand
Jede
Jetzt erscheint d
KZU
KZU-Baugruppe
Kanal
Kanal-Ersatzschaltung
Kanalbeziehung
Kanalbeziehungen
Kanalbit-Zuordnung
Kanalbit-Zuordnung für den 64-kbit/s-Kanal
Kanalnummer
Kanalverbindungen
Kanäle
Kapitel
Karte
Karten
Kartenersatzschaltung
Kategorien
Kennz
Kennzeichen
Kennzeichenbits
Klammern
Klicken
Klicken Sie
Klicken Sie auf die Schaltfläche <
Klicken Sie doppelt auf dieses Symbol.
Klicken Sie in der Konfigurationsmaske mit der linken Maustaste auf die Kurzbezeichnung der Baugruppe.
Klicken Sie mit der linken Maustaste auf d
Knoten
Knoten-
Knoten.
Knotenbestückung
Knotendaten
Knoteninfo"
Knoteninformation
Knotenkonfiguration
Knotennr.
Knotennummer
Knotens
Kommandofenster
Kommandos
Kommunikation
Konfigur
Konfiguration
Konfiguration DSK-Baugruppe
Konfiguration ISDN-Baugruppe
Konfiguration K
Konfiguration Port-Baugruppe
Konfiguration einer Baugruppe
Konfigurations
Konfigurations-Dump-Funktionen
Konfigurationsdatei
Konfigurationsdaten
Konfigurationsmaske
Konfigurieren einer CC8-Verbindung "synchron V.110" in einem
Konfigurieren einer CC8-Verbindung mit n x 64 kbit im Anfangs- und Endknoten
Konfigurieren eines neuen Knotens
Konfigurieren von CC8-Verbindungen
Kontrollzwecken.
Kopier
Kopieren
Kopieren einer Kanalbeziehung
Kopieren einer Knotenkonfiguration
Kurzbezeichnung
Kurzübersicht
Kurzübersicht der Debug-Befehle
Kurzübersicht der Soft-ABM Befehle
LAN (1) als
LAN (2) als
Lade Eingaben
Laden
Laden der QD2-Firmware
Laden einer Firmware
Laden eines Debuggingbefehls
Ladevorgang
Ladezustand
Lastabwehr
Laufwerk
Leerzeichen
Legen
Leistungsmerkmale
Leitungsersatzschaltung
Leitungstest
Liste
Listfeld
Lösche Eingaben
Lösche Meldungen
Löschen
MDV
MSP
MSP-Software
MSP-Software Installation
MSP-XMP1-Applikation
Maske
Maske Kanalbeziehungen
Maske,
Maustaste
Mehrfachausnutzung eines 64-kbit/s-Kanals mit CC8-Datenmultiplexer
Meldefenster
Meldekennung
Meldewort
Meldewortbearbeitung
Meldeworte
Meldewortes durch Eingabe der Kanalbeziehung für Kanal 0
Meldung
Meldungen
Meldungsfenster
Menuecode 4
Menü
Menüpunkt
Menüunterpunkt
Messergebnis
Mit
Mod. DSK
Modul
Modulbestückung
Module
Modus
Multip
Multipolling
Multipolling-Umsetzer
Multipollingstrecke
Mögliche
Möglichkeit
Nach
Nach Abschluß des Speicherns erscheint die Meldung.
Nachdem Sie die
Nachricht
Name
Namen
Netz
Netzelement
Netzmanager
Neu
Neue Leistungsmerkmale ab der Version 3.6
Neuen Knoten eingeben
Normal
Normalbetrieb
Normale Konfiguration
Nummer
Offline
Offline Sitzung
Offline-Modus
Offline-Sitzung
Online
Online Sitzung
Online-Modus
Online-Sitzung
PC 9 polig
PCM-
Parameter
Passwort
PeC (Persistance Check)
Pegel
Pegel an
Pfad
Pinbelegung
Polling
Pollingstrecke
Popup-Menü
Port
Port-Baugruppe
Ports
Portschnittstelle
Priorität
Programm
Programmteile
Prozent
Prozessor
Prüfschleife
Prüfung
QD2
QD2-Adapter
QD2-Firmware
Quittung
Quittung"
README-Datei
Rahmen
Rahmensynchronismus
Refresh-Timer
Reset
Ringpolling
Rufen Sie
Rufen Sie für die Baugruppe, für die Sie eine CC8-Verbindung konfigurieren wollen, die Maske "Konfiguration Baugruppe" auf.
Rufen Sie i
Rufen Sie im Hauptmenü "Bedienung" den Menüunterpunkt "
Rufen Sie im Hauptmenü "Bedienung" den Menüunterpunkt "Debugging Soft-ABM" auf. Die Maske "Debugging und Soft-ABM" wird angezeigt.
Rufen Sie in der Maske "Konfiguration" im Menüpunkt "Bearbeiten" den Menüunterpunkt "Taktprioritäten" auf.
Rufnummer
Rufnummern für wahlfähige Umsetzer vergeben
Ruhestellung
Rückmeldung
SISA
SISA-Nummer
Sammel
Schalten
Schalten auf die aktive Ebene
Schalten auf eine spezielle Ebene
Schalterstellungen
Schaltfläche
Schleife
Schnittstelle
Schnittstelleninformation
Schreibende Debugging-Funktion
Schreibfunktion
Schriftzug
Sende
Sende-
Sende- und Empfangspegel
Senderichtung
Service
Setup-Programm
Sichern
Sicherung
Sie
Sie können
Sie können aber auch den Eintrag im Listfeld auswählen und auf die Schaltfläche <Ändern> klicken, der Istzustand wird dann ebenfalls geändert.
Sie können jetzt eine weitere Taktquelle auswählen und für diese eine Taktpriorität vergeben.
Sie können nun entscheiden, ob Sie die Konfigurationsdaten im Knoten mit den Daten aus der Konfiguration überschreiben wollen.
Sie müssen
Signal
Signalausfall
Sitzung
Sitzung starten
So führen Sie einen Leitungstest durch
So löschen Sie eine Taktpriorität
So stellen Sie den Sende- und Empfangspegel ein
So stellen Sie eine Rufnummer ein
So vergeben Sie eine Taktpriorität
So versenden Sie "Text mit Quittung"
So versenden Sie "Text ohne Quittung"
So versenden Sie einen Debugging-/Soft-ABM-Befehl
So wird ein Umsetzer als beschaltet gekennzeichnet
So wird eine GWF Einmessung durchgeführt
So ändern Sie das Passwort allgemein
So ändern Sie das Passwort für die Knotennummer
So ändern Sie eine Taktpriorität
Soft-ABM
Soft-ABM"
Soft-ABM-Befehle
Soft-ABM-Kommandostruktur
Software
Softwarevoraussetzungen
Soll
Sonderfall
Speichere Meldungen
Speichern
Speichern der Ausgabedaten
Speicherplatz
Sperrzeit
Sprache
Standard
Start
Startbit
Starte Refresh-Timer
Starten
Starten des CD Setup-Programms
Steckbrücke
Steckplatz
Steckplatzinfo
Steckplatzinformation
Steckplatznummer
Steckplätze
Steckverbinder
Stimmt die Knotennr. des Knotens nicht mit der Knotennr. der konfigurierten Daten überein, dann wird folgende Maske angezeigt. In dieser Maske wird die Knotennr. des angeschlossenen Knotens (Knoten Nr. Gerät) und die Knotennr. der Daten (Knoten Nr. Daten
Stimmt die Knotennummer des angeschlossenen Knotens und die Knotennummer der konfigurierten Daten überein, dann werden die Daten an den Knoten übertragen.
Strecke
Stromquelle/A
Stromsenke/A
Stromversorgungen
Subadresse
Symbol
Symbolleiste der Hauptmaske
Synchron mit V.110 Rahmen
Synchron n x 64k
Syntax
Sys-Kanal
System
Systemkanaleinstellung
TELEBRAS
Tabelle
Taktpriorität
Taktprioritäten
Taktquelle
Taste
Teilnehmer
Test
Test Gegenport
Test lokal
Testabschnitte
Text
Textdatei
Texte
Therm. Verlustlei
Tragen Sie im
Tragen Sie im Eingabefeld die
Transparent
Typ
Umschalt
Umsetzen
Umsetzer
Umsetzer A Umsetzer
Umsetzer/Port beschalten
Umsetzernummer
Umsetzers
Unter
Unterstation
V.110
V.110"
V.24
Variante
Verbindung
Verbindungskabel
Vereinfachung
Verfügung
Vergabe
Verifikation"
Verknüpfung
Verknüpfung der D-Kanäle
Verl
Verlassen Sie das Fenster mit <Ok>.
Verlassen Sie die Maske mit <Übernehmen>.
Verlustleistung
Vermittlungsinformation
Vers
Version
Verwendung
Verzeichnisse
Voreinstellung
Vorgang
Vorgehensweise
Vorrangverbindung
Vorzug
Vorzugslage
WINDOWS
Watt
Weise
Welche Dateien werden installiert?
Wenn
Wenn die
Werden
Werte
Wie
Wird
Wurde
Wählen
Wählen Sie
Wählen Sie aus dieser Liste die zu bestückende Baugruppe aus.
Wählen Sie den Button "
Wählen Sie den Button "Debugging / Soft-ABM" aus.
Wählen Sie den Steckplatz der Baugruppe
Wählen Sie den Umsetzer
Wählen Sie die
Wählen Sie im Listfeld
Wählen Sie im Listfeld "Frequenz" die Bitrate aus.
Während
Während dieser Zeit erscheint das Meldefenster "Warten XMP1 Speichern".
XMP1
XMP1 Holen
XMP1 Speichern
XMP1"
XMP1-
XMP1-Knoten
Y-Bits
ZWR
Zeichen
Zeigen/Drucken
Zeigt die
Zeit
Zeitschlitz
Zeitschlitz 16 als Kanal 31 (K31)
Zentr. Steckplatzinfo
Zentrale Steckplatzinformation
Zentrale-
Zentrale-/Dezentrale Steckplatzinformation
Zentralteil
Ziffern
Zum Bilden der
Zuordnung
Zusammen
Zustand
Zwischen-Knoten
Zwischenknoten
abbrechen
aber
abfragen
abgefragt
abgegeben
abgehenden
abgelegt.
abgerufen.
abgeschlossen
abgleichen
abhängig
ablegen
acht
akt
aktiv:
aktive
aktivieren
aktiviert
aktuelle
aktuellen
alle
allerdings
allgemein
als
an,
an.
andere
anderen
ange
angegeben
angeordnet
angepaßt
angeschl.
angeschlossen
angeschlossenen
angezeigt
angezeigt.
anklicken
ankommendem
anschließend
anzeig
anzu
anzugeben.
auch
auch:
auf
auf.
aufgeführt
aufgelistet
aufgelöst
aufgerufen
aufgrund
aufrufen
aus
aus.
ausge
ausgedruckt
ausgeführt
ausgefüllte
ausgeg
ausgegeben.
ausgelagert
ausgeschaltet
ausgesendet.
ausgewählt
ausgewählte
auswählen
auszu
automatisch
bedeutet:
beende
befindet
beginn
bei
beide
beim
belegt
beliebig
benannt
benutzt
benötigt
benötigt.
benötigte
bereit
beschalten
beschaltet
beschalteten
beschr
besitzt
bestehen
besteht
bestimmte
bestätig
bestückbaren
bestücken
bestückt
bestückten
beteiligt
betr
betätigen
bezeichnet
bis
bisherigen
bit/s
bleibt
bzw.
c:\sisa\vb\
c:\windows\system\
dadurch
damit
dann
darauf
darf
dargestellt
das
dazu
daß
deaktivier
definiert
dem
den
denen
der
des
dezentrale
dezentralen
die
dient
dies
diese
diesem
diesen
dieser
dieses
direkt
disable
doppelt
drei
drücken
durch
durchführen
durchgeführt
durchgeschaltet
durchzuführen
ebenfalls
eigentlich
ein
ein.
eine
einem
einen
einer
eines
einfach
eingeb
eingefügt.
eingegeben
eingegebenen
eingemessen
einges
eingestellt
einget
eingetragen,
eingetragen.
eingetragenen
einmal
einmessen
einschalten
einstellbar
einstellen
einzeln
einzelnen
einzugeben
empf
entfern
entfällt
enthalten
enthält
entscheiden
entsprechend
entweder
erfolgen
erfolgreich
erfolgt
erforderliche
ergibt
erhalten
erkannt
erleichter
ermittel
ermöglich
erscheint
ersetzt
erste
erstellen
erweitert
erweiterte
erweiterten Konfiguration
erzeugen
erzeugt
eschaltet" gekennzeichnet wurden.
fehlende
fehlerfrei
female (Buchse)
festgelegt
festlegen
folg
folgende
folgenden
folgender
folgendermaßen
fortgesetzt.
frei
freien
führ
fünf
für
für Übertragung benutzt
geben
gebildet
gedoppelt
geführt
geholt
gekennzeichnet
geladen
gelten
gelöscht
geprüft.
geschaltet
geschaltet.
geschlossen
geschrieben
gesendet
gesetzt
gesichert.
gespeichert
gestartet
get
gewählte
gewünschte
gezeigten
geändert
geöffnet
ggf.
gleich
gleich Ersatz
gleich Ersatzlage" geschaltet.
gleich Vorzug
gleich Vorzugslage" die Übertragung durchgeführt. Ist diese wieder fehlerfrei, dann wird nicht wieder zurückgeschaltet. Die Übertragung erfolgt weiterhin über diese Portschnittstelle.
gleich Vorzugslage" wieder fehlerfrei ist, dann wird nicht auf diese zurückgeschaltet.
gleiche
grau
haben
haben,
handelt
hier
hierbei
hierfür
hierzu
hin
holen
ihre
immer
indem
installiert
internen
ist
ist,
ist.
jede
jedoch
jetzt
jeweils
kHz
kHz:
kann
kbit
kbit-Verbindung
kbit/s
kein
keine
kennzeichnet
klicken
komm
konfigurieren
konfiguriert
konfigurierten
kontrollier
kopier
können
können.
laden
laden.
lassen
law_
letzte
liegen.
linken
lokal
löschen
manuell
maximal
mehr
mehrere
menuecode
mindestens
mit
modifizier
modulabhängig
modular
momentan
muß
möchte
möglich
möglich.
müssen
n+4
nach
nebeneinander
nein
neue
neuen
neuer
nicht
noch
normal
normale
normalen
normalen Konfiguration
notwendig
nun
nur
nächste
oberen
oder
offline"
ohne
ok>.
online
opt
organisiert
parallel
passiv
passiven
phasenstarre
physikalische
polig
prüfen
quittier
reset
ruffähigen
sch
schalten
schaltet
sein.
selbständig
selekt
sende
serielle
set_
setz
sich
siehe auch:
sind
sind.
sofern
sofort
soll,
soll.
sollen.
sollte
sondern
sowie
speichern
sperren
speziell
start
steckt.
stehen
steht
stellen
stellt
synchron
transparent
türkis
umgeschaltet
umschalten
unbekannt
und
und/oder
unge
unter
unterbrochen
unterschiedliche
unterteilt.
ver
veranlaßt
verbunden
verfügbaren
vergeben
verlassen.
verschiedene
versende
verwendet
vom
von
von einem anderen Port durchgeschaltet.
vor
vorgenommen
vorgeschlagene
vorhanden
vorko
vorliegen
vornehmen
wahlfähige
weiter
weitere
welche
wenn
werden
werden,
werden.
werden:
wie
wieder
wird
wird.
wirk
wobei
wollen
wurde
wurden.
wählbar
wählen
z.B.
zeigt
zentrale
zentralen
zu den
zuerst
zugeordnet
zum
zur
zurückgeschaltet.
zurückgeschleift.
zusammen
zusätzlich
zwei
zweite
zwischen
Änder
Änderungen
Öffnen Sie d
Über
Über diese Portschnittstelle wird bei einem Fehler der
Über diese Portschnittstelle wird bei einem Fehler der Vorzugslage die Übertragung durchgeführt. Wenn die Vorzugslage wieder fehlerfrei ist, dann wird auf diese zurückgeschaltet.
Über diese Portschnittstelle wird im fehlerfreien Betrieb die Übertragung durchgeführt. Im Fehlerfall wird auf die
Übernahme
Übernehmen
Überprüfen Sie die eingegebenen Daten. Mit <Eintrag ok> werden die konfigurierten Daten in das Listfeld übernommen.
Übersicht über die Debugging-Kommandostruktur
Übersicht über die Soft-ABM-Kommandostruktur
Übertragung
Übertragungsstrecke
ändern
ändernden
öffnen
öffnet
über
überein,
übernommen
überschreiben
übertragen
